FROM alpine:3.17.1

RUN apk add --no-cache \
    autoconf \
    automake \
    gcc \
    gdb \
    libtool \
    linux-headers \
    make \
    musl-dev \
    wget

RUN cd /tmp && wget http://download.redis.io/releases/redis-6.0.9.tar.gz -O redis.tar.gz \
    && tar -zxvf redis.tar.gz \
    && cd redis-6.0.9 && make noopt \
    && cp ./src/redis-server /bin/ \
    && cp ./src/redis-cli /bin/ \
    && rm -rf redis.tar.gz && rm -rf redis-6.0.9
